vim.api.nvim_set_keymap('n', '<leader>w', '<C-w>', { noremap=true, silent = false})
vim.api.nvim_set_keymap('n', '<leader>a', '<C-w>h', { noremap=true, silent = false})
vim.api.nvim_set_keymap('n', '<leader>l', '<C-w>l', { noremap=true, silent = false})
vim.api.nvim_set_keymap('n', '<leader>d', ':bd!<CR>', { noremap=true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>w/', ':vertical sb<CR>', { noremap=true, silent = false})
vim.api.nvim_set_keymap('n', '<leader>w-', ':split<CR>', { noremap=true, silent = false})
vim.api.nvim_set_keymap('n', '<leader>tt', ":FloatermToggle<CR>", { noremap=true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>tn', ":FloatermNew<CR>", { noremap=true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>t;', ":FloatermPrev<CR>", { noremap=true, silent = true})
vim.api.nvim_set_keymap('t', '<ESC>', "<C-\\><C-n>", { noremap=true, silent = true})
vim.api.nvim_set_keymap('n', '<leader>gg', ":LazyGit<cr>", { silent = true, desc = 'LazyGit window' })
--vim.api.nvim_set_keymap('n', '<D-/>', ":<cr>", { silent = true, desc = 'Comment like in vscode' })
